/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunipharma.gui;

import com.tunipharma.dao.ServiceDAO;
import com.tunipharma.entities.Service;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ferdawes
 */
public class Accpet_service extends javax.swing.JFrame {

    /**
     * Creates new form Accpet_service
     */
    Service service = new Service();

    ServiceDAO servicedao = new ServiceDAO();

    public Accpet_service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        but_igno_serv = new javax.swing.JButton();
        but_accpt_serv1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Acceptation d'un service");

        but_igno_serv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but_igno_serv.setText("Ignorer");

        but_accpt_serv1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but_accpt_serv1.setText("Accepter");
        but_accpt_serv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_accpt_serv1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but_accpt_serv1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_igno_serv))
                    .addComponent(jLabel1))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_igno_serv)
                    .addComponent(but_accpt_serv1))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_accpt_serv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_accpt_serv1ActionPerformed
        if (evt.getActionCommand().equals("Accepter")) {
            Service service = new Service();
            servicedao.findServiceById(service.getId());
            service.setEtat("active");
            JOptionPane.showMessageDialog(this, "Acceptation effectué avec succés");
        }
    }//GEN-LAST:event_but_accpt_serv1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_accpt_serv1;
    private javax.swing.JButton but_igno_serv;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
