/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunipharma.gui;

import com.tunipharma.dao.ServiceDAO;
import com.tunipharma.entities.Service;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ferdawes
 */
public class Ajouter_service extends javax.swing.JPanel {

    /**
     * Creates new form Ajouter_service
     */
    Service service=new Service();

    ServiceDAO servicedao = new ServiceDAO();

    public Ajouter_service() {
        initComponents();
        initCategorie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catégorie_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Combo_ajout = new javax.swing.JComboBox();
        ajout_nom_servi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc_ajou_serv = new javax.swing.JTextArea();
        but_ajouter_serv = new javax.swing.JButton();
        but_annuler_serv1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        otherCategorie = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(800, 579));
        setMinimumSize(new java.awt.Dimension(800, 579));
        setPreferredSize(new java.awt.Dimension(800, 579));

        catégorie_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        catégorie_label.setText("Catégorie :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nom de service :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Description :");

        Combo_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_ajoutActionPerformed(evt);
            }
        });

        ajout_nom_servi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_nom_serviActionPerformed(evt);
            }
        });

        desc_ajou_serv.setColumns(20);
        desc_ajou_serv.setRows(5);
        jScrollPane1.setViewportView(desc_ajou_serv);

        but_ajouter_serv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but_ajouter_serv.setText("Ajouter");
        but_ajouter_serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_ajouter_servActionPerformed(evt);
            }
        });

        but_annuler_serv1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but_annuler_serv1.setText("Annuler");
        but_annuler_serv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_annuler_serv1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Ajouter service");

        otherCategorie.setMaximumSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(but_ajouter_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(but_annuler_serv1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(catégorie_label))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ajout_nom_servi, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Combo_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(otherCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(418, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(catégorie_label)
                                    .addComponent(Combo_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(otherCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(ajout_nom_servi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_ajouter_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_annuler_serv1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void but_ajouter_servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_ajouter_servActionPerformed
        if (evt.getActionCommand().equals("Ajouter")) {
            Service service = new Service();
           if( 1!=Combo_ajout.getSelectedIndex()){
               JOptionPane.showMessageDialog(this, "Champs catégorie vide ");
           }
           else{
            if (Combo_ajout.getSelectedItem().toString().equals("----------Other----------")) {
                service.setCategorie(otherCategorie.getText());
            } else {
                service.setCategorie(Combo_ajout.getSelectedItem().toString());
            }
            if(ajout_nom_servi.getText().length()==0)
            {
            
           
            JOptionPane.showMessageDialog(this, "Champs nom vide");
            }
            else {
                 service.setNom(ajout_nom_servi.getText());
            }
                  if(desc_ajou_serv.getText().length()==0)
            {
            
            
            JOptionPane.showMessageDialog(this, "Champs despcription vide");
            }
            else {
                       
            service.setDescription(desc_ajou_serv.getText());
                  
            service.setEtat("active");
            servicedao.insertService(service);
            initValues();
            initCategorie();
               JOptionPane.showMessageDialog(this, "Ajout effectué avec succés");
        }
     
        }}
    }//GEN-LAST:event_but_ajouter_servActionPerformed
    private void initCategorie() {
        ServiceDAO serviceDAO = new ServiceDAO();
        if (Combo_ajout.getSelectedIndex() != -1) {
            Combo_ajout.removeAllItems();
        }
        List<String> listec = serviceDAO.getAllCategories();
        for (String c : listec) {
            Combo_ajout.addItem(c);
        }
        Combo_ajout.addItem(new String("----------Other----------"));
        otherCategorie.setVisible(false);
    }

    private void initValues() {
        otherCategorie.setText("");
        Combo_ajout.setSelectedIndex(0);
        ajout_nom_servi.setText("");
        desc_ajou_serv.setText("");
    }

    private void Combo_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_ajoutActionPerformed
        if (evt.getActionCommand() == "comboBoxChanged") {
            if (Combo_ajout.getSelectedItem() != null && Combo_ajout.getSelectedItem().toString().equals("----------Other----------")) {
                otherCategorie.setVisible(true);
                revalidate();
            } else {
                otherCategorie.setVisible(false);
                revalidate();
            }
        }
    }//GEN-LAST:event_Combo_ajoutActionPerformed

    private void but_annuler_serv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_annuler_serv1ActionPerformed
   if (evt.getActionCommand().equals("Annuler")) {
            initValues();
        }
    }//GEN-LAST:event_but_annuler_serv1ActionPerformed

    private void ajout_nom_serviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_nom_serviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajout_nom_serviActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_ajout;
    private javax.swing.JTextField ajout_nom_servi;
    private javax.swing.JButton but_ajouter_serv;
    private javax.swing.JButton but_annuler_serv1;
    private javax.swing.JLabel catégorie_label;
    private javax.swing.JTextArea desc_ajou_serv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField otherCategorie;
    // End of variables declaration//GEN-END:variables

}
