/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunipharma.gui;

//import static com.tunipharma.util.MyLdapConnection.verifStatut;
import com.tunipharma.dao.PharmacieDAO;
import com.tunipharma.entities.Pharmacie;
import static com.tunipharma.util.MyLdapConnection.*;
import java.awt.Color;

import javax.swing.JOptionPane;

/**
 *
 * @author PLAYER9
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    EspaceClient ec = null;

    public Authentification() {
        initComponents();

    }

    public void setEc(EspaceClient ec) {
        this.ec = ec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_pwd = new javax.swing.JPasswordField();
        text_login = new javax.swing.JTextField();
        button_valider = new javax.swing.JButton();
        button_annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("Mot de passe");

        text_pwd.setForeground(new java.awt.Color(205, 204, 216));
        text_pwd.setText("PASSWORD");
        text_pwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_pwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_pwdMousePressed(evt);
            }
        });

        text_login.setForeground(new java.awt.Color(205, 204, 216));
        text_login.setText("LOGIN");
        text_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_loginMousePressed(evt);
            }
        });

        button_valider.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        button_valider.setText("Valider");
        button_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_validerActionPerformed(evt);
            }
        });

        button_annuler.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        button_annuler.setText("Annuler");
        button_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_mainLayout = new javax.swing.GroupLayout(Panel_main);
        Panel_main.setLayout(Panel_mainLayout);
        Panel_mainLayout.setHorizontalGroup(
            Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_mainLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_mainLayout.createSequentialGroup()
                        .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_login)
                            .addComponent(text_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addComponent(button_annuler))
                .addGap(18, 18, 18)
                .addComponent(button_valider)
                .addContainerGap())
        );
        Panel_mainLayout.setVerticalGroup(
            Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_mainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_annuler)
                    .addComponent(button_valider))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_validerActionPerformed
        String ch, sh;
        ch = this.text_login.getText();
        sh = new String(this.text_pwd.getPassword());
        String res = verifStatut(ch, sh);
        //String res = "admin";
        if (res.equals("admin")) {
            new MainInterface().setVisible(true);
            this.setVisible(false);
            if (ec != null) {
                ec.setVisible(false);
            }
            this.dispose();
        } else {
            if (res.equals("pharmacien")) {
                int idN = Integer.parseInt(getIdNb(ch, sh));
                PharmacieDAO pharmacieDAO = new PharmacieDAO();
                Pharmacie p = pharmacieDAO.findPhamacieByPharmacien(idN);
                System.out.println("**" + p.getPharmacien().getNom() + "**");
                new Menu_pharmacien(p).setVisible(true);
                this.setVisible(false);
                if (ec != null) {
                    ec.setVisible(false);
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Authentification échoué !!!");
            }
        }
    }//GEN-LAST:event_button_validerActionPerformed

    private void button_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_annulerActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_button_annulerActionPerformed

    private void text_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_loginMousePressed
        if (text_login.getText().equals("LOGIN")) {
            text_login.setText("");
            text_login.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_text_loginMousePressed

    private void text_pwdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_pwdMousePressed
        String sh = new String(this.text_pwd.getPassword());
        if (sh.equals("PASSWORD")) {
            text_pwd.setText("");
            text_pwd.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_text_pwdMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_main;
    private javax.swing.JButton button_annuler;
    private javax.swing.JButton button_valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField text_login;
    private javax.swing.JPasswordField text_pwd;
    // End of variables declaration//GEN-END:variables

}
