/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunipharma.gui;

import com.tunipharma.dao.ServiceDAO;
import com.tunipharma.entities.Service;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferdawes
 */
public class ListeService extends javax.swing.JPanel {

    String etat;

    ServiceDAO serviceDAO = new ServiceDAO();

    /**
     * Creates new form ListeService
     */
    public ListeService(String etat){
        this.etat = etat;
        initComponents();
        intialiseJTable();
         initCategorie();
    }

    ListeService(Service findServiceById) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     private void initCategorie() {
        ServiceDAO serviceDAO = new ServiceDAO();
        if (combo_list_serv.getSelectedIndex() != -1) {
            combo_list_serv.removeAllItems();
        }
        List<String> listec = serviceDAO.getAllCategories();
        for (String c : listec) {
            combo_list_serv.addItem(c);
        }
       
        
    }

    public void intialiseJTable() {
        DefaultTableModel model = (DefaultTableModel) listeServices.getModel();
        List<Service> services = serviceDAO.DisplayAllService(etat);
        for (Service service : services) {
            model.addRow(new Object[]{service.getId(), service.getNom(), service.getCategorie()});
        }
        listeServices.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_list_serv = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nom_serv_rech = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeServices = new javax.swing.JTable();
        Butt_rech_servi = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Liste des services");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Catégorie:");

        combo_list_serv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        combo_list_serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_list_servActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nom de service :");

        listeServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom de service", "Catégorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeServices.setColumnSelectionAllowed(true);
        listeServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeServicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeServices);
        listeServices.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listeServices.getColumnModel().getColumn(0).setResizable(false);
        listeServices.getColumnModel().getColumn(1).setResizable(false);
        listeServices.getColumnModel().getColumn(2).setResizable(false);

        Butt_rech_servi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Butt_rech_servi.setText("Chercher");
        Butt_rech_servi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_rech_serviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(combo_list_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(nom_serv_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(Butt_rech_servi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_list_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nom_serv_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Butt_rech_servi)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Butt_rech_serviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt_rech_serviActionPerformed
        // TODO add your handling code here:

        if (evt.getActionCommand().equals("Chercher")) {
            DefaultTableModel model = (DefaultTableModel) listeServices.getModel();
            model.setRowCount(0);
            List<Service> services = serviceDAO.DisplayAllService(etat);
            
            String nom = nom_serv_rech.getText().toLowerCase();
            String catg = combo_list_serv.getSelectedItem().toString().toLowerCase();

            for (Service serv : services) {
                if ((nom.isEmpty() || nom.equals(serv.getNom().toLowerCase()))
                        && (catg.isEmpty() || catg.equals(serv.getCategorie().toLowerCase()))) {
                    model.addRow(new Object[]{serv.getId(),serv.getNom(), serv.getCategorie()});
                }
            }
            listeServices.setModel(model);
        }
    }//GEN-LAST:event_Butt_rech_serviActionPerformed

    private void listeServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeServicesMouseClicked
        // TODO add your handling code here:
           if (evt.getClickCount() == 2) {
            DefaultTableModel model = (DefaultTableModel) listeServices.getModel();
            final int id = (int) model.getValueAt(listeServices.getSelectedRow(), 0);
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                        new Modifier_service(serviceDAO.findServiceById(id)).setVisible(true);
                }

            });
        }
    }//GEN-LAST:event_listeServicesMouseClicked

    private void combo_list_servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_list_servActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_list_servActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butt_rech_servi;
    private javax.swing.JComboBox combo_list_serv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeServices;
    private javax.swing.JTextField nom_serv_rech;
    // End of variables declaration//GEN-END:variables

}
