/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunipharma.gui;

import com.tunipharma.util.MyConnection;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author KINGMOEZHAJ
 */
public class Rapports extends javax.swing.JPanel {

    /**
     * Creates new form Rapports
     */
    public Rapports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBestPh = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 579));
        setMinimumSize(new java.awt.Dimension(800, 579));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Générer des Rapports");

        jBestPh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBestPh.setText("Meilleure Pharmacie");
        jBestPh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBestPhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBestPh, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBestPh)
                .addContainerGap(412, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBestPhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBestPhActionPerformed
        if (evt.getActionCommand().equals("Meilleure Pharmacie")) {
            try {
                JasperDesign jasperDesign = JRXmlLoader.load("rapports/bestpharmacie.jrxml");

                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                // - Paramètres à envoyer au rapport
                java.util.Map parameters = new HashMap();
                parameters.put("Titre", "Titre");
                // - Execution du rapport
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, MyConnection.getInstance());
                JFileChooser dialogue = new JFileChooser(new File("."));
                File fichier;
                if (dialogue.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    fichier = dialogue.getSelectedFile();
                    if (fichier.getPath().substring(fichier.getPath().length() - 4).equals(".pdf") == false) {
                        JasperExportManager.exportReportToPdfFile(jasperPrint, fichier.getPath()+".pdf");
                        String[] commande = {"C:\\Program Files (x86)\\Adobe\\Reader 11.0\\Reader\\AcroRd32.exe", fichier.getPath()+".pdf"};
                        Runtime.getRuntime().exec(commande);

                    } else {
                        JasperExportManager.exportReportToPdfFile(jasperPrint, fichier.getPath());
                        String[] commande = {"C:\\Program Files (x86)\\Adobe\\Reader 11.0\\Reader\\AcroRd32.exe", fichier.getPath()};
                        Runtime.getRuntime().exec(commande);
                    }

                }
                // - Création du rapport au format PDF

            } catch (    JRException | IOException ex) {
                Logger.getLogger(Rapports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBestPhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBestPh;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
